name: Deploy Nuxt App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy viw SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" << 'EOF'
            cd /var/www/GF-website
            cat > .env <<EOL
          EMAILJS_SERVICE_ID=${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_TEMPLATE_ID=${{ secrets.EMAILJS_TEMPLATE_ID }}
          EMAILJS_PUBLIC_TOKEN=${{ secrets.EMAILJS_PUBLIC_TOKEN }}
          EOL
            git pull origin main
            npm install
            npm run build
            pm2 restart gf-website
          EOF
